#spring.datasource.url=jdbc:h2:file:/Users/lamanh/IdeaProjects/KinoXP/data/testdb;AUTO_SERVER=TRUE
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create
#spring.h2.console.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/kinodatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=lamanh
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.h2.console.enabled=false
//mysqlbuprojekteqoshul
