spring.datasource.url=jdbc:h2:file:/Users/lamanh/IdeaProjects/KinoXP/data/testdb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
